INSERT INTO ACCOUNT(NAME, PASSPORTNUMBER) VALUES ('Rihanna', 'PS24564');
INSERT INTO ACCOUNT(NAME, PASSPORTNUMBER) VALUES ('Beyonce', 'AJD1917');

INSERT INTO TRANSACTION(ACCOUNTID, TRANSACTIONTYPE, VALUE) VALUES (1, 1, 100.00);
INSERT INTO TRANSACTION(ACCOUNTID, TRANSACTIONTYPE, VALUE) VALUES (2, 1, 120.00);
INSERT INTO TRANSACTION(ACCOUNTID, TRANSACTIONTYPE, VALUE) VALUES (2, 1, 50.00);